ALTER TABLE cards
    ALTER COLUMN rarity TYPE VARCHAR(50)
    USING rarity::VARCHAR(50);

ALTER TABLE sets
    ALTER COLUMN type TYPE VARCHAR(50)
    USING type::VARCHAR(50);

ALTER TABLE card_legalities
    ALTER COLUMN format TYPE VARCHAR(50)
    USING format::VARCHAR(50),
    ALTER COLUMN status TYPE VARCHAR(50)
    USING status::VARCHAR(50);

